### ISSUE TITLE
Alphabetical order problems in indexes

### ISSUE THREAD

**Issue by ejtaal** [ejtaal/aa#18]
The check indexes script currently produces the following output:
# Comparison for file 'aa-aan-index.js':

Index of 732 lines looks well sorted and OK!! :)
# Comparison for file 'aa-br-index.js':

Index of 1064 lines looks well sorted and OK!! :)
# Comparison for file 'aa-ha-index.js':

Index of 897 lines looks well sorted and OK!! :)
# Comparison for file 'aa-hw3-index.js':

Problems found in this index at the following locations:
hw_c[0][0] =    Title
hw_c[1][0] =    Intro
hw_c[4][0] =    Ta
hw_c[5][0] =    Tha
hw_c[6][0] =    Jim
hw_c[7][0] =    _Ha
hw_c[8][0] =    Kha
hw_c[10][0] =   Dhal
hw_c[11][0] =   Ra
hw_c[12][0] =   Za
hw_c[13][0] =   Seen
hw_c[14][0] =   Sheen
hw_c[15][0] =   Saad
hw_c[17][0] =   _Ta
hw_c[19][0] =   Ain
hw_c[20][0] =   Ghain
hw_c[22][0] =   Qaf
hw_c[27][0] =   Ha
hw3[35]=اسو
hw3[194]=حصر
hw3[300]=دعي
hw3[458]=سويد
hw3[676]=عم
# Comparison for file 'aa-hw4-index.js':

Index of 1301 lines looks well sorted and OK!! :)
# Comparison for file 'aa-imn-index.js':

Problems found in this index at the following locations:
imn[485] = ردد
imn[489] = ردد
imn[498] = رسح
imn[1186] = كتت
imn[1221] = كلي
imn[1277] = لقع
imn[1385] = نثط
imn[1393] = نجب
imn[1556] = عزن
imn[1592] = end
imn[1593] = end
imn[1594] = end
# Comparison for file 'aa-kaz-index.js':

Index of 3030 lines looks well sorted and OK!! :)
# Comparison for file 'aa-la-index.js':

Problems found in this index at the following locations:
la[9]=ابل
la[379]=بحي
la[625]=جثا
la[2194]=شتي
la[2505]=صنبر
la[2514]=صهم
la[2801]=علت
la[2990]=عضج
la[3273]=غضر
la[3763]=قهلبس
la[3891]=كنكع
# Comparison for file 'aa-ll-index.js':

Problems found in this index at the following locations:
ll_p[303]=بهو
ll_p[584]=حرو
ll_p[777]=خسو
ll_p[797]=خضوم
ll_p[1068]=رث[رت]
ll_p[1360]=سلو
ll_p[1552]=شتج
ll_p[1599]=شطن
ll_p[1627]=شقع
ll_p[1776]=صمخ
ll_p[1882]=ضعث
ll_p[2338]=غرو
ll_p[2339]=غرو
ll_p[2537]=فلد
ll_p[2573]=قب
ll_p[2724]=كدس
ll_p[2826]=مدث
ll_p[3078]=يلب
ls_p[3]=ق
ls_p[4]=قبل
ls_p[5]=قتن
ls_p[6]=قدم
ls_p[7]=قرطف
ls_p[8]=قرن
ls_p[9]=قشف
ls_p[10]=قضى
ls_p[11]=قطف
ls_p[12]=قفو
ls_p[13]=قلق
ls_p[14]=قنفذ
ls_p[15]=قول
ls_p[16]=قوم
ls_p[17]=قوى
ls_p[18]=ك
ls_p[19]=كحل
ls_p[20]=كرم
ls_p[21]=كشف
ls_p[22]=كفهر
ls_p[23]=كلف
ls_p[24]=كن
ls_p[25]=كن
ls_p[26]=كن
ls_p[27]=لا
ls_p[28]=لثو
ls_p[29]=لحم
ls_p[30]=لزم
ls_p[31]=لعق
ls_p[32]=لفو
ls_p[33]=لقى
ls_p[34]=لهزم
ls_p[35]=لون
ls_p[36]=لون
ls_p[37]=متع
ls_p[38]=مثل
ls_p[39]=مثل
ls_p[40]=مسك
ls_p[41]=مشى
ls_p[42]=مطى
ls_p[43]=مل
ls_p[44]=من
ls_p[45]=منع
ls_p[46]=موق
ls_p[47]=موق
ls_p[48]=نبه
ls_p[49]=نجو
ls_p[50]=نخل
ls_p[51]=نزع
ls_p[52]=نزل
ls_p[53]=نسم
ls_p[54]=نضو
ls_p[55]=نعق
ls_p[56]=نعم
ls_p[57]=نفى
ls_p[58]=نقى
ls_p[59]=نهك
ls_p[60]=نول
ls_p[61]=نول
ls_p[62]=هجن
ls_p[63]=هجن
ls_p[64]=هضم
ls_p[65]=هم
ls_p[66]=هنم
ls_p[67]=هيق
ls_p[68]=هيق
ls_p[69]=وتن
ls_p[70]=وجه
ls_p[71]=وخم
ls_p[72]=ورق
ls_p[73]=وسع
ls_p[74]=وسم
ls_p[75]=وصل
ls_p[76]=وضع
ls_p[77]=وغل
ls_p[78]=وقع
ls_p[79]=وقف
ls_p[80]=ولس
ls_p[81]=ولى
ls_p[82]=وهن
ls_p[83]=وهن
# Comparison for file 'aa-mgf-index.js':

Problems found in this index at the following locations:
mgf[81] = ام
mgf[82] = ام
# Comparison for file 'aa-pr-index.js':

Index of 167 lines looks well sorted and OK!! :)
# Comparison for file 'aa-sg-index.js':

Problems found in this index at the following locations:
sg[67]=اسط
sg[117]=ائس
sg[171]=بيا
sg[276]=جاد
sg[287]=حذف
sg[293]=حرى
sg[465]=رئى
sg[829]=فيز
sg[921]=كيع
sg[999]=مرا
sg[1105]=ميج
# Comparison for file 'aa-ulq-index.js':

Problems found in this index at the following locations:
ulq[335]=ان
ulq[846]=روم
ulq[847]=رهب
ulq[848]=رهط
ulq[849]=رهن
ulq[850]=رهو
ulq[1016]=شعف
ulq[1840]=ياجوج
# Comparison for file 'aa-umj-index.js':

Index of 937 lines looks well sorted and OK!! :)
# Comparison for file 'aa-umr-index.js':

Problems found in this index at the following locations:
umr[146] = بوب
umr[147] = بوب
umr[177] = ثمم
umr[206] = جلل
umr[452] = راي
umr[453] = راي
umr[454] = راي
umr[455] = راي
umr[465] = زيت
umr[534] = سيح
umr[536] = سير
umr[543] = سيل
umr[544] = سال
umr[546] = سين
umr[550] = سوا
umr[551] = سوا
umr[552] = سوا
umr[567] = شطن
umr[592] = title
umr[849] = فيع
umr[955] = كفا
umr[1010] = ميد
umr[1011] = ميل
umr[1040] = ملا
umr[1042] = منن
umr[1043] = منن
umr[1135] = هلل
umr[1143] = هيت
umr[1145] = ها
umr[1212] = ي
# Comparison for file 'aa-ums-index.js':

Problems found in this index at the following locations:
ums[23] = اخو
ums[153] = جرز
ums[494] = شرر
ums[510] = صرف
ums[786] = كفا
ums[787] = كفر
ums[788] = كسل
ums[789] = كشف
ums[790] = كسب
ums[791] = كسع
ums[794] = كمد
ums[795] = كمم
ums[796] = كلم
ums[797] = كلي
ums[798] = كلب
ums[799] = كلل
ums[900] = ندي
# Comparison for file 'aa-uqa-index.js':

Problems found in this index at the following locations:
uqa[159]=رعي
uqa[190]=سخر
uqa[259]=ضطر
# Comparison for file 'aa-uqw-index.js':

Problems found in this index at the following locations:
uqw[205] = تلا
uqw[208] = تاج
uqw[235] = جثال
uqw[272] = جلع
uqw[488] = حوق
uqw[1346] = قضي
uqw[1532] = محض
# Comparison for file 'aa-vi-index.js':

Problems found in this index at the following locations:
vi[75] = بتر
vi[93] = ثكن
vi[99] = جعل
vi[293] = قضف

**Comment by AsimIqbal2nd** [comment]
Comparison for file 'aa-aan-index.js':
Problems found in this index at the following locations:
aan[44]=امر  Solution rename aan[45]=امر 
aan[56]=ايك Solution rename aan[57]=ايي
aan[125]=حجث Solution rename aan[125]=حدث
aan[424]=عفو Solution rename aan[425]=عفو sacrifice root  عفف 
aan[521]=قسور Solution rename aan[521]=قسر  
aan[679]=نفب  Solution rename aan[679]=نقب
aan[682]=نكل Solution rename aan[682]=نكد
aan[723]=وصل  Solution rename aan[724]=وصي
Comparison for file 'aa-br-index.js':
Problems found in this index at the following locations:
br[84]=اني Solution: rename br[84]=انني and br[85]=اني
br[95]=ايوب  Solution: rename br[92]=اين and  br[95]=اييم and  br[96]=ايين sacrifice
br[96]=اين See above solution
br[204]=خهل  Solution: rename br[204]=جهل
br[205]=خوب Solution: rename br[205]=جوب

Comparison for file 'aa-imn-index.js':
Problems found in this index at the following locations:
imn[485] = ردد Solution: rename imn[485]=رد
imn[489] = ردد Solution: rename imn[489]=ردن
imn[498] = رسح Solution: rename imn[498]=رشح
imn[1186] = كتت  Solution: rename imn[1186]=كت
imn[1221] = كلي Solution: rename imn[1221]=كلا
imn[1277] = لقع  Solution: rename imn[1277]=لفع
imn[1385] = نثط Solution: rename imn[1386]=نجث
imn[1393] = نجب Solution: rename imn[1393]=نحب
imn[1556] = عزن Solution: rename imn[1556]=وزن
imn[1592] = end Solution: rename imn[1592]=يييي or remove the image
imn[1593] = end Solution: rename imn[1593]=يييي or remove the image
imn[1594] = end Solution: rename imn[1594]=يييي or remove the image

Comparison for file 'aa-la-index.js':
Problems found in this index at the following locations:
la[9]=ابل Seems OK, can you check Br. Ejtaal
la[379]=بحي Solution: rename la[379]=بهي
la[625]=جثا  Solution: rename la[625]=جشا
la[2194]=شتي Solution: rename la[2195]=شثن
la[2505]=صنبر Solution: rename la[2506]=صنج
la[2514]=صهم Solution: rename la[2514]=صهتم
la[2801]=علت Solution: rename la[2801]=عتل
la[2990]=عضج Solution: rename la[2990]=عضنج
la[3273]=غضر Solution: rename la[3273]=غفر
la[3763]=قهلبس Solution: rename la[3763]=قهبلس
la[3891]=كنكع Solution: rename la[3891]=كعنكع
Comparison for file 'aa-ll-index.js':
Problems found in this index at the following locations: Generate test separately on LL and LS and share results, I have only corrected LL since LS seems to be comparing with LL thus giving many entries wrong
ll_p[303]=بهو Solution: rename ll[303]=بهرج
ll_p[584]=حرو Solution: rename to حرد
ll_p[777]=خسو Solution: rename  to خسر
ll_p[797]=خضوم Solution: rename to خضع
ll_p[1068]=رث[رت] Solution: rename to رتب
ll_p[1360]=سلو Solution: rename to سح
ll_p[1552]=شتج Solution: rename to شجب
ll_p[1599]=شطن Solution: rename NEXT IMAGE TO شظي
ll_p[1627]=شقع Solution: rename to شقر
ll_p[1776]=صمخ Solution: rename to صمي
ll_p[1882]=ضعث Solution: rename toضغث
ll_p[2338]=غرو Solution: rename to غرز 
ll_p[2339]=غرو Solution: rename to غرض 
ll_p[2537]=فلد Solution: rename to فلي
ll_p[2573]=قب Solution: rename NEXT IMAGE TO قبح
ll_p[2724]=كدس Solution: rename to كمثر
ll_p[2826]=مدث Solution: rename to ملح
ll_p[3078]=يلب Solution: rename NEXT IMAGE TO  يوح

Comparison for file 'aa-mgf-index.js':
Problems found in this index at the following locations:
mgf[81] = ام Solution: rename mgf[81]=ايم
mgf[82] = ام Solution: rename mgf[82]=ايم

Comparison for file 'aa-sg-index.js':
Problems found in this index at the following locations:
sg[67]=اسط  Solution: rename  sg[67]=اصط
sg[117]=ائس Solution: rename sg[117]=ايس
sg[171]=بيا Solution: rename sg[172]=بير
sg[276]=جاد Solution: rename sg[276]=حاد
sg[287]=حذف Solution: rename sg[288]=حرث
sg[293]=حرى Solution: rename sg[294]=حزم
sg[465]=رئى Solution: rename sg[465]=ريي
sg[829]=فيز Solution: rename sg[830]=فيي
sg[921]=كيع Solution: rename sg[922]=922
sg[999]=مرا Seems OK, br Ejtaal can you check
sg[1105]=ميج Solution: rename sg[1106]=ميز
Comparison for file 'aa-ulq-index.js':
Problems found in this index at the following locations:
ulq[335]=ان Solution: rename ulq[335]=انن and  ulq[336]=انني
ulq[846]=روم Solution: rename ulq[846]=رود sacrificed روع and روم 
ulq[847]=رهب Solution: rename ulq[847]=رود sacrificed رهب
ulq[848]=رهط Solution: rename ulq[848]=رود sacrificed رهط
ulq[849]=رهن Solution: rename ulq[849]=رود sacrificed رهق and رهن 
ulq[850]=رهو Solution: rename ulq[850]=رود sacrificed رهو
ulq[1016]=شعف Solution: rename ulq[1016]=شغف
ulq[1840]=ياجوج Solution: rename ulq[1840]=ياس  sacrificed ياجوج

Comparison for file 'aa-umr-index.js':
Problems found in this index at the following locations:
umr[146] = بوب Solution: rename umr[148]=بوي and umr[149]=بوي sacrificed بوا
umr[147] = بوب Solution: rename umr[148]=بوي and umr[149]=بوي sacrificed بوا
umr[177] = ثمم  Solution: rename umr[177]=ثم
umr[206] = جلل Solution: rename umr[206]=جل
umr[452] = راي Solution: rename umr[452]=ريي sacrificed راي
umr[453] = راي Solution: rename umr[453]=ريي sacrificed راي
umr[454] = راي  Solution: rename umr[454]=ريي sacrificed راي
umr[455] = راي Solution: rename umr[455]=ريي sacrificed راي
umr[465] = زيت Solution: rename umr[465]=زهق sacrificed  زيت
umr[534] = سيح Solution: rename umr[534]=سوح sacrificed سيب / سيح
umr[536] = سير Solution: rename umr[536]=سور sacrificed  سير
umr[543] = سيل Solution: rename umr[543]=سول sacrificed سيل 
umr[544] = سال Solution: rename umr[544]=سول sacrificed سال 
umr[546] = سين Solution: rename umr[546]=سون sacrificed سين 
umr[550] = سوا Solution: rename umr[550]=سوي  sacrificed سوا 
umr[551] = سوا Solution: rename umr[551]=سوي  sacrificed سوا 
umr[552] = سوا Solution: rename umr[552]=سوي  sacrificed سوا 
umr[567] = شطن Solution: rename umr[568]=شطي sacrificed شطا
umr[592] = title Solution: rename umr[592]=شيع or remove this page
umr[849] = فيع Solution: rename umr[849]=فيا
umr[955] = كفا Solution: rename umr[955]=كفي sacrificed  كفا
umr[1010] = ميد Solution: rename umr[1010]=ماد  sacrificed ميد and ميا
umr[1011] = ميل Solution: rename umr[1011]= مال  sacrificed مير/ميز/ميل
umr[1040] = ملا Solution: rename umr[1040]=ملي sacrificed ملا
umr[1042] = منن Solution: rename umr[1042]=من
umr[1043] = منن Solution: rename umr[1043]=من
umr[1135] = هلل Solution: rename umr[1135]=هل
umr[1143] = هيت Solution: rename umr[1144]=هيي
umr[1145] = ها Solution: rename umr[1145]=هيي
umr[1212] = ي Solution: rename umr[1212]=ييي
Comparison for file 'aa-ums-index.js':
Problems found in this index at the following locations:
ums[23] = اخو Solution: rename ums[23]=اخا
ums[153] = جرز  Solution: rename ums[153]=جزر
ums[494] = شرر Solution: rename ums[494]=شور
ums[510] = صرف Solution: rename ums[511]=صري
ums[786] = كفا Solution: UMS PDF had pages 786 to 799 arranged in wrong sequence due to which PDF generated image names wrongly, the corrected images were uploaded on https://drive.google.com/folderview?id=0B0z4SgcNMpK6RWMyYVpiQlA4cG8&usp=sharing Download images from there and re upload on site and also regenerate index using the excel there. Same solution for below images till 799 OR I sent email for required images, just replace those 15 images. 
ums[787] = كفر See above
ums[788] = كسل See above
ums[789] = كشف See above
ums[790] = كسب See above
ums[791] = كسع See above
ums[794] = كمد See above
ums[795] = كمم See above
ums[796] = كلم See above
ums[797] = كلي See above
ums[798] = كلب See above
ums[799] = كلل See above
ums[900] = ندي See above
Comparison for file 'aa-uqa-index.js':
Problems found in this index at the following locations:
uqa[159]=رعي Solution: rename uqa[159]=رصد
uqa[190]=سخر Solution: rename uqa[190]=سبل
uqa[259]=ضطر  Solution: rename uqa[259]=ضرر
Comparison for file 'aa-uqw-index.js':
Problems found in this index at the following locations:
uqw[205] = تلا Solution: rename uqw[205]=تلي
uqw[208] = تاج Solution: rename uqw[208]=توج
uqw[235] = جثال Solution: rename uqw[236]=جثي
uqw[272] = جلع Solution: rename uqw[272]=جلح
uqw[488] = حوق Solution: rename uqw[488]=خوق
uqw[1346] = قضي Solution: rename uqw[1346]=قلب
uqw[1532] = محض Solution: rename uqw[1532]=مخض
Comparison for file 'aa-vi-index.js':
Problems found in this index at the following locations:
vi[75] = بتر Solution: rename vi[75]=بطر
vi[93] = ثكن Solution: rename vi[93]=ثخن
vi[99] = جعل Seems OK, can you check Br. Ejtaal
vi[293] = قضف Solution: rename vi[293]=قذف

LS and HW3 need to be checked by Br Ejtaal

**Comment by ejtaal** [comment]
Nothing major in the latest check after some updates and fixes to the index.
