### ISSUE TITLE
search box retaining previous search

### ISSUE THREAD

**Issue by AsimIqbal2nd** [ejtaal/aa#20]
Search box maintains previous search when opened again, it must show blank search box for new search, as currently  previous search has to be deleted before entering new root for search

**Comment by ejtaal** [comment]
In all popular browsers I've tried, the text is selected so you can type over straight away, no need to delete. If you found a browser which doesn't do this by default please post here, so we can see the impact of it. By keeping it it allows for correcting of a mistake (for instance you meant Drb instead of dhrb).

**Comment by AsimIqbal2nd** [comment]
I used opera, you can test on its latest version.

**Comment by ejtaal** [comment]
Hmm opera seems to be odd one out then. A shame to break default behaviour for a minority browser. I can make it an option in the menu.

**Comment by ejtaal** [comment]
Now implemented in dev.
