### ISSUE TITLE
images not loading without refresh sometimes

### ISSUE THREAD

**Issue by AsimIqbal2nd** [ejtaal/aa#21]
Sometimes the images are not loading and no image is loaded or previous image is retained even if we push next button many times. 

Maybe images need to be put in same directory, somehow images are not fetched sometimes on some instances maybe out of sync due to different locations.

**Comment by AsimIqbal2nd** [comment]
I am using opera for viewing almanac and also for downloaded version.

**Comment by ejtaal** [comment]
There is now a debugging option in the menu. If you enable it you can see the new images that are supposed to be loading. If they are added in the debug field but the image itself isn't loading then this indicates the browser is unable to load it due to some network issue. The website does experience throttled traffic so try again later. If the problem persists, let me know.
